src/components/program-settings.js, src/constants/program-settings.js
Program module, changing setting name and title from `event period` to `event date`.
=> fix: change program setting from event period to event date

i18n/en.pot, src/components/dataSet-settings.js, src/components/dialog/dialog-first-launch.js, src/components/program-settings.js, src/constants/data-set-settings.js, src/constants/program-settings.js, src/pages/layout.js, src/styles/Button.module.css, src/utils/api.js
This PR has:
First launch where a configuration has not yet been saved. The user must take explicit action to save the default configuration to get started. The first-launch state also provides an opportunity to clearly state the consequences of applying settings in this app.
In this PR I'm having troubles to handle states, I want to set state after all promises are resolved so the dialog closes and the general section is shown. I hope you can give me an idea of how to solve it.
=> Feat: First launch dialog

src/components/sidebar.js
This PR fixes [Jira 8800](https://jira.dhis2.org/browse/DHIS2-8800) by handling currentSection as a state an not as a variable
=> fix: current section doesnt match with route

i18n/en.pot, src/components/sections/user-sync-test/run-test.js, src/components/sections/user-sync-test/user-sync-test-container.js, src/constants/test-android.js
**Description**
Add the number of TEI reserved value to user sync test
jira issue: [DHIS2-9156](https://jira.dhis2.org/browse/DHIS2-9156)
**Solution description**   
- Get value from datastore (general_settings, teiReservedValue)
- Show value and recommended value
=> feat: [DHIS2-9156] Add TEI reserved value to user sync test

package.json
Set the version in `package.json` to update the app version for the app store
=> fix: update app version

i18n/en.pot, src/constants/dataset-appearance.js, src/constants/menu-sections.js, src/pages/Appearance/Datasets/DatasetGlobalSettings.js, src/pages/Appearance/Datasets/DatasetsAppearance.js, src/pages/Appearance/Datasets/helper.js
Appearance: Data set screen Section ([DHIS2-11022](https://jira.dhis2.org/browse/DHIS2-11022))
- Table with settings options (Period, Organisation Unit, Sync status)
- Save and reset buttons
- Save JSON using the format:
{
completionSpinner: {
globalSettings: {},
specificSettings: {},
},
filterSorting: {
home: {},
dataSetSettings: {
globalSettings: {},
specificSettings: {},
},
programSettings: {},
},
}
=> feat: [DHIS2-11022] Create Data set Appearance Section 

i18n/en.pot, src/constants/menu-sections.js, src/pages/Synchronization/Datasets/DatasetGlobalSettings.js, src/pages/Synchronization/Datasets/DatasetSyncSettings.js
Synchronization: Dataset Section ([DHIS2-10597](https://jira.dhis2.org/browse/DHIS2-11076))
- Table row with global setting option: Maximum number of periods to download (number-input)
- Save and reset buttons
- Save JSON using the format:
```
"dataSetSettings": {
"globalSettings": {
"periodDSDownload": 11
},
"specificSettings": {}
}
```
=> feat: [DHIS2-11076] Dataset Synchronization Section

src/components/field/MatomoId.js, src/components/field/MatomoUrl.js, src/pages/General/DisableSettings.js, src/pages/General/GeneralSettings.js
General: Authorities
- Inputs should be disabled if the user has not all authorities
- Strip button footer (save and reset) should be disabled if the user has not all authorities
=> feat: general section, disable inputs if user has not all authorities

package.json, yarn.lock
Bumps @dhis2/ui from 5.7.2 to 6.10.5
=> chore: bump dhis2/ui from 5.7.2 to 6.10.5

i18n/en.pot, src/components/dialog/DialogDelete.js, src/components/dialog/DialogEncrypt.js, src/components/dialog/DialogSaveData.js, src/components/field/ReservedValues.js, src/components/inputs/InputNumber.js, src/components/sections/user-sync-test/run-test.js, src/components/sections/user-sync-test/test-android.js, src/components/sections/user-sync-test/user-sync-test-container.js, src/pages/Synchronization/Programs/SpecificSettings.js
The current PR has:
- update import components, from ui-core to ui
=> fix: migrate import from ui-core to ui

i18n/en.pot, src/components/analyticVisualization/SelectProgram.js, src/components/analyticVisualization/VisualizationGroup/GroupType.js, src/components/analyticVisualization/VisualizationGroup/NewGroup.js, src/components/analyticVisualization/VisualizationGroup/RadioGroup.js, src/components/analyticVisualization/VisualizationGroup/SelectGroup.js, src/components/analyticVisualization/VisualizationGroup/VisualizationGroup.js, src/components/analyticVisualization/VisualizationGroup/styles/GroupField.module.css, src/components/analyticVisualization/VisualizationGroup/styles/GroupType.module.css, src/components/analyticVisualization/VisualizationTitle.js, src/components/analyticVisualization/index.js, src/components/field/SelectField.js, src/pages/Analytics/Program/DialogVisualization.js, src/pages/Analytics/Program/NewProgramVisualization.js, src/pages/Analytics/Program/ProgramAnalytics.js, src/pages/Analytics/Program/ProgramAnalyticsList.js, src/pages/Analytics/Program/helper.js, src/utils/useSystemId.js
This PR has:
- Basic components such as Text field to add a title or name a visualization and Select program
- Query to generate a random id
- Radio Group: 
- new group that shows a text field
- field to select a group that has been created previously
_Dialog to add visualization_
_Title field_
_Group field_
=> feat: [DHIS2-11261] Add new visualization for programs

i18n/en.pot, src/components/analyticVisualization/VisualizationTable/HomeVisualizationTable.js, src/components/analyticVisualization/VisualizationTable/VisualizationRow.js, src/components/analyticVisualization/index.js, src/constants/info.js, src/constants/menu-sections.js, src/pages/Analytics/Home/HomeAnalyticList.js, src/pages/Analytics/Home/HomeAnalytics.js
This PR contains:
- Basic layout: Home visualization section
- Table to show groups and visualizations
_Basic layout_
_Table with groups and visualizations_
=> feat: [DHIS2-11254] Show home groups and visualizations

i18n/en.pot, src/components/analyticVisualization/VisualizationTable/DatasetTable.js, src/components/analyticVisualization/index.js, src/constants/menu-sections.js, src/pages/Analytics/Dataset/DatasetAnalyticList.js, src/pages/Analytics/Dataset/DatasetAnalytics.js, src/pages/Analytics/Dataset/DatasetVisualizationQuery.js, src/pages/Analytics/Dataset/helper.js
This PR contains:
- Basic layout: Data set visualization section
- Table to show groups and visualization
_Basic layout_
_Table with groups and visualization_
=> feat: [DHIS2-11263] create basic layout for data set

i18n/en.pot, src/components/analyticVisualization/VisualizationGroup/RadioGroup.js, src/pages/Analytics/Home/DialogVisualization.js, src/pages/Analytics/Home/HomeAnalyticList.js, src/pages/Analytics/Home/NewHomeVisualization.js, src/pages/Analytics/Home/helper.js
This PR contains:
- Dialog to add home visualizations: 
- Search visualization
- Add title
- Select group 
_Add home visualization_
=> feat: [DHIS2-11255] Add visualization and groups

src/pages/Analytics/Dataset/DatasetVisualizationQuery.js
More info here: https://jira.dhis2.org/browse/DHIS2-12307
=> fix: Change param to 'paging' instead of 'pager'

src/utils/validators/__tests__/isValidURL.test.js, src/utils/validators/isValidURL.js
This PR has:
valid URL should have:
- must start with either HTTP or HTTPS and
- length (2, 256)
- contains domain like .com, .org etc.
Note: I closed the previous PR because it had a Semantic error and disabled the "Merge" button.
=> fix: valid URL has http or https protocol

package.json
This PR has: update the app version to `2.1.1`
=> feat: update patch app version

deploy_settings_app.sh
This script allows you to deploy the android settings app to a specific dhis2 server automatically.
**This script will run on Bitrise: Steps**
1) Check entry variables and find zip
2) Show list of apps
3) Upload to a specific server if credentials are right
=> feat: Add bash script for automatic deployment

i18n/en.pot, src/pages/Home/Home.js, src/pages/Home/Home.module.css, src/pages/Home/Section.js
This PR adds a tag that displays the current android settings version.
[DHIS2-12633](https://jira.dhis2.org/browse/DHIS2-12633)
_Version tag_
=> feat: add webapp version to overview page

src/components/analyticVisualization/VisualizationUserTest/VisualizationUserTest.js, src/components/analyticVisualization/VisualizationUserTest/visualizationQuery.js
This PR has: 
- fix: when running the user test for visualization, the process was not working because there was no query result
- change function to read query 
_User test running_
=> fix: visualization query for user test [DHIS2-13124]

src/pages/Appearance/Datasets/DialogDatasetSpecificSetting.js, src/pages/Appearance/Programs/DialogNewProgram.js, src/pages/Synchronization/Datasets/DialogSpecificSettings.js, src/pages/Synchronization/Programs/DialogSpecificSetting.js
This PR adjust the width of some Select components like program and dataset selection
=> fix: [program dataset] adjust component width

src/components/field/TrackerImporter.js
This PR adjusts the label text.
[DHIS2-13265](https://jira.dhis2.org/browse/DHIS2-13265)
=> feat: change label New Tracker Importer [Sync Settings: Global]

src/components/field/MessageOfDay.js, src/components/field/TextAreaField.js
These two imports were still using the old style imports.
=> fix(prop-types): change old style imports to new prop-types

package.json
Add missing peer dependencies.
=> chore(deps): add peer dependencies

i18n/en.pot, src/components/analytics/VisualizationElement.js, src/pages/Analytics/TEI/AnalyticsTEI.js, src/pages/Analytics/TEI/helper.js
This PR keeps "None" from the list of periods supported in analytics TEI, but should save this period as null in DataStore
[DHIS2-13808](https://dhis2.atlassian.net/browse/DHIS2-13808)
=> fix: remove None period analytics

package.json, yarn.lock
=> chore: update ui dependencies

src/auth/AuthWall.js, src/auth/useAndroidSettingsVersion.js
This PR helps the datastore ASWA version to be updated and the same as the most recent android settings webapp version.
[DHIS2-14108](https://dhis2.atlassian.net/browse/DHIS2-14108)
[DHIS2-14108]: https://dhis2.atlassian.net/browse/DHIS2-14108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: keep datastore ASWA version updated

src/components/field/FileMaxSize.js, src/modules/populateDefaultSettings.js, src/pages/Synchronization/Global/helper.js, src/utils/getByteLength.js
This PR allows setting up the default value to null instead of 0.
[DHIS2-17548](https://jira.dhis2.org/browse/DHIS2-17548)
_Default value null_
_Data store null_
[DHIS2-17548]: https://dhis2.atlassian.net/browse/DHIS2-17548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: set null as default value of maximum file size [DHIS2-17548]

i18n/en.pot, src/constants/appearance-settings.js, src/pages/Appearance/Datasets/DatasetSpecificSettings.js, src/pages/Appearance/Datasets/DatasetsAppearance.js, src/pages/Appearance/Datasets/DialogDatasetSpecificSetting.js, src/pages/Appearance/Datasets/NewDatasetSettings.js, src/pages/Appearance/Datasets/SpecificSettings.js, src/pages/Appearance/Datasets/SpecificTableAction.js, src/pages/Appearance/Datasets/helper.js, src/pages/Appearance/appearanceDatastoreQuery.js
This PR configures the maps/location for dataSets (only specific settings).
[DHIS2-18022](https://jira.dhis2.org/browse/DHIS2-18022)
[DHIS2-18023](https://jira.dhis2.org/browse/DHIS2-18023)
- Disable manual location capture (checkbox)
- Minimum location accuracy (m) (number input field)
- Same behavior of Program capture coordinates settings
_Capture coordinates DataSets_
_Edit settings_
[DHIS2-18022]: https://dhis2.atlassian.net/browse/DHIS2-18022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18023]: https://dhis2.atlassian.net/browse/DHIS2-18023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: dataSet capture coordinates specific settings  [DHIS2-18022]

i18n/en.pot, src/pages/Appearance/Programs/QuickActionsSettings.js
Implements [DHIS2-17937](https://dhis2.atlassian.net/browse/DHIS2-17937)
Add Quick Actions Bar Configuration to Appearance Settings
**Description:**
Change key and label for Deactivate action to Cancel Enrollment.
[DHIS2-17937]: https://dhis2.atlassian.net/browse/DHIS2-17937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change key and label for cancel enrollment

package.json, src/components/field/__tests__/ReservedValues.test.js, src/components/field/__tests__/SmsGateway.test.js, yarn.lock
Implements [DHIS2-18972](https://dhis2.atlassian.net/browse/DHIS2-18972) and [DHIS2-18973](https://dhis2.atlassian.net/browse/DHIS2-18973)
[DHIS2-18972]: https://dhis2.atlassian.net/browse/DHIS2-18972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-18973]: https://dhis2.atlassian.net/browse/DHIS2-18973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add tests for reservedvalues and smsgateway components
