i18n/en.pot, src/components/android-settings-container.js, src/components/android-settings.js, src/components/dialog-encrypt.js, src/constants/android-settings.js
This PR has:
Fixing the double click for `encryptDB` switch. At the beginning sometimes it needed to double click switch to change the state from checked to not checked.
=> fix: double click for change encryptDB state

src/constants/android-settings.js
This PR has:
General settings constants:
- `metadataSync`: remove option 1h and 12h
=> fix: change metadata and data sync constant

src/components/sections/dataset/dataSet-settings.js, src/components/sections/program/program-settings.js, src/modules/getItemFromList.js, src/modules/removeSettingFromList.js
This PR fixes a [Jira issue](https://jira.dhis2.org/browse/DHIS2-8793), the specific program/data set choice disappears when:
Steps:
1. Program/ Data set settings
2. Click Add program/data set a specific setting
3. Choose Antenatal Care Visit/Art summary monthly  and click Add/Save
4. Click Edit
5. Change the value and click Add/Save
6. Click Delete and confirm
7. Open Add program/data set specific setting. Notice that item is now missing from the menu
=> fix: specific setting program and data set choice disappears

src/components/sections/general/android-settings-container.js
This PR deletes an extra function for remove namespace. 
This bug was found after merging the previous PR, an extra function was left and that made the app crash.
=> fix: change delete namespace function

i18n/en.pot, src/constants/android-settings.js
**Description**
The app has different labels for data and metadata sync options. 
Sync options should be the same as in the app.
[jira issue DHIS2-9302](https://jira.dhis2.org/browse/DHIS2-9302)
**Solution description**
Change labels for sync options:
Data options:
Webapp | APP
-- | --
24h | 1 Day
7d | 1 Week
Metadata options:
Webapp | APP
-- | --
30m | 30 Minutes
1h | 1 Hour
6h | 6h
12h | 12h
24h | 1 Day
=> fix: [DHIS2-9302] change labels metadata and data options

i18n/en.pot, src/components/dialog/dialog-manual-alert.js, src/components/notice-alert.js, src/components/sections/general/general-settings.js, src/constants/android-settings.js, src/modules/general/useGeneralForm.js
Add manual option to Sync Metadata and Data
- when clicking on the manual option, an alert dialog should pop up
- if click on OK, the manual option will be selected
- if click on Cancel, the previous option will remain selected
- This option only available from android app version 2.3.0 onwards
**Alert Dialog Text:** 
```
By selecting Manual there will NOT be any AUTOMATIC SYNCHRONIZATION of data. Your users will need to sync manually for data to be sent to the server. Do you want to select this option?'
```
[JIRA DHIS2 9301](https://jira.dhis2.org/browse/DHIS2-9301)
=> fix: [DHIS2-9301] add Manual option to sync

i18n/en.pot, src/components/dialog/dialog-manual-alert.js, src/components/sections/general/general-settings.js, src/constants/android-settings.js
Change Manual dialog's text to: 
"By selecting Manual there will NOT be any AUTOMATIC SYNCHRONIZATION of metadata. your users will need to download the metadata manually. "
The dialog should say "metadata" or "data"
=> fix: manual dialog text

i18n/en.pot, src/components/analyticVisualization/VisualizationTable/GroupVisualizationRow.js, src/components/analyticVisualization/VisualizationTable/ProgramTable.js, src/components/analyticVisualization/VisualizationTable/VisualizationRow.js, src/components/analyticVisualization/VisualizationTable/VisualizationTable.js, src/components/analyticVisualization/VisualizationTable/VisualizationTable.module.css, src/components/analyticVisualization/VisualizationTable/helper.js, src/components/analyticVisualization/index.js, src/components/dialog/DialogDeleteElement.js, src/pages/Analytics/Program/ProgramAnalytics.js, src/pages/Analytics/Program/ProgramAnalyticsList.js, src/pages/Analytics/Program/ProgramVisualizationQueries.js, src/pages/Analytics/Program/helper.js
The current PR has:
- Show Program visualization separated by program and group.
- Delete a visualization group
- Delete a visualization
- Update datastore
_Visualization table by programs_
_Visualization by groups_
_Visualizations_
=> feat: show and delete group and visualizations

i18n/en.pot, src/components/analyticVisualization/SelectDataset.js, src/components/analyticVisualization/index.js, src/pages/Analytics/Dataset/DatasetAnalyticList.js, src/pages/Analytics/Dataset/DialogVisualization.js, src/pages/Analytics/Dataset/NewDatasetVisualization.js, src/pages/Analytics/Dataset/helper.js
This PR has:
- Dialog to add home visualizations:
- Search visualization
- Add title
- Select group
=> feat: add Data set visualization and groups

src/pages/Synchronization/Datasets/datasetQueries.js, src/pages/Synchronization/Programs/programQueries.js
Change Program and Data set sync settings API call.
From: `filter: 'access.data.write:eq:true'`
To: `filter: 'access.read:eq:true'`
=> fix: [DHIS2-12253] [synchronization] change filter data to metadata program dataset

src/components/field/TrackerImporter.js, src/pages/Synchronization/Global/GlobalSettings.js, src/pages/Synchronization/Global/helper.js
This PR has:
Previous scenario:
Synchronization Global: After changing to other sections, the Tracker Importer checkbox remains unchecked even if it was checked and saved before.
Solution: Checked the tracker importer version before rendering the components
V1 = default version
V2 = new tracker importer
_Datastore_
=> fix: checkbox remains unchecked

src/pages/Analytics/Home/HomeAnalyticList.js, src/pages/Analytics/Home/HomeAnalytics.js
This PR seeks to correct the following:
when new visualizations were added, they were not saved in the correct format, which caused errors when displaying the table and lost information.
Fixed by checking the difference between the list of initial visualizations and the list of recently added views each time a change is made.
_Data wrongly saved an empty visualization group_
_Data saved after fixing bug_
=> fix: verify new visualization group and format datastore

src/constants/appearance-settings.js
This PR changes the appearance key to the new format:
```
"programConfiguration": {
"globalSettings": {
"completionSpinner": true
},
"specificSettings": {
"programUID": {
"completionSpinner": false,
"optionalSearchl": true
}
}
}
```
=> fix: change datastore key appearance

src/components/field/GlobalProgramCompletion.js, src/constants/appearance-settings.js
This PR fixes the appearance key (globalSettings) to the new format:
```
"programConfiguration": {
"globalSettings": {
"completionSpinner": true
},
"specificSettings": {
"programUID": {
"completionSpinner": false,
"optionalSearchl": true
}
}
}
```
=> fix: change datastore completion spinner key appearance

src/components/field/OptionalTEISearch.js, src/constants/appearance-settings.js, src/pages/Appearance/Datasets/DatasetsAppearance.js, src/pages/Appearance/Home/HomeAppearance.js, src/pages/Appearance/Programs/ProgramsAppearance.js, src/pages/Appearance/Programs/helper.js, src/pages/Appearance/appearanceDatastoreQuery.js
This PR fixes:
- the optional search checkbox label
- the appearance key (globalSettings), to support different android versions by reintroducing `completionSpinner` key to datastore query and initial values:
```
"completionSpinner": {
"globalSettings": {
"visible": true
},
"specificSettings": {
"programUID": {
"visible": false,
}
}
}
```
=> fix: appearance add completion spinner key to datastore json

src/components/field/TrackerImporter.js
This PR has:
- only show the new tracker importer checkbox from 2.38v
- adjust label text
=> feat: [DHIS2-12632] new tracker importer only suport for 2.38v

src/components/dialog/DialogDisableSettings.js, src/pages/General/DisableSettings.js
This PR updates the "Disable all settings" help and Modal text, including the current Android Settings Webapp sections.
_Disable all settings button and helpText_
_Modal_
=> fix: [general] update disable settings helptext

src/components/analytics/VisualizationElement.js, src/constants/data-set-settings.js, src/pages/Synchronization/Datasets/SpecificSettings.js, src/pages/Synchronization/Datasets/helper.js
This PR fixes the period labels in Data set Synchronization and TEI Analytics section.
_Data set synchronization_
_TEI Analytics periods_
=> fix: change fixed period labels

src/components/analyticVisualization/VisualizationSearch/ItemSelector.js, src/components/analyticVisualization/VisualizationSearch/helper.js, src/components/analyticVisualization/VisualizationSearch/visualizationQuery.js
This PR improves the list of visualizations, showing all visualizations, and disabling visualizations that can't be used in the Android app.
[DHIS2-13381](https://jira.dhis2.org/browse/DHIS2-13381)
_Visualization list:_
=> feat: improve visualization list

src/components/analyticVisualization/VisualizationSearch/ItemSearchField.js, src/components/analyticVisualization/VisualizationSearch/styles/ItemSearchField.module.css, src/pages/Synchronization/UserSyncTest/searchField/ItemSearchField.js, src/pages/Synchronization/UserSyncTest/searchField/styles/ItemSearchField.module.css, src/styles/Layout.module.css
Implements [DHIS2-15139](https://dhis2.atlassian.net/browse/DHIS2-15139)
- Add left margin to Clear buttons.
- Limit container size
_Clear button_
_Container_
[DHIS2-15139]: https://dhis2.atlassian.net/browse/DHIS2-15139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: styles add margin and align elements

src/components/field/ReservedValues.js, src/pages/General/helper.js
This PR allows users to set the value 0 for reserved values. In case there is no value set, it uses the default value.
[DHIS2-15652](https://dhis2.atlassian.net/browse/DHIS2-15652)
=> fix: allow set 0 reserved values [DHIS2-15652]

src/components/analytics/VisualizationType.js, src/pages/Analytics/TEI/helper.js
This PR keeps the same behavior for all visualization-type options by holding the name and short name even after selecting the WHO nutrition radio button.
[DHIS2-16370](https://jira.dhis2.org/browse/DHIS2-16370)
_Single Value visualization type_
_WHO nutrition visualization type_
[DHIS2-16370]: https://dhis2.atlassian.net/browse/DHIS2-16370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: title and short name fields empty who nutrition

src/pages/Synchronization/UserSyncTest/helper.js
This PR fixes the no value bug when User Sync test runs without results for some users.
[DHIS2-16348](https://jira.dhis2.org/browse/DHIS2-16348)
_Fixed User sync test_
_Error empty array_
[DHIS2-16348]: https://dhis2.atlassian.net/browse/DHIS2-16348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: user sync test runs without results

i18n/en.pot, src/components/dialog/DialogBypass.js, src/components/field/BypassDHIS2Version.js, src/components/field/index.js, src/pages/General/GeneralSettings.js, src/pages/General/helper.js
This PR allows users to skip DHIS2 supported versions validation.
[DHIS2-15905](https://jira.dhis2.org/browse/DHIS2-15905)
_Uncheck Bypass version_
_Dialog Bypass version_
_Check Bypass version_
_Dialog Require validation_
[DHIS2-15905]: https://dhis2.atlassian.net/browse/DHIS2-15905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: bypass DHIS2 version [DHIS2-15905]

src/pages/Appearance/Home/HomeAppearance.js, src/pages/Appearance/Programs/ProgramsAppearance.js
This PR add `dataSetConfiguration` key when updating the home and program appearance.
The `dataSetConfiguration` key was created to configure the maps/location for dataSets (only specific settings).
[DHIS2-19025](https://jira.dhis2.org/browse/DHIS2-19025)
[DHIS2-19025]: https://dhis2.atlassian.net/browse/DHIS2-19025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add dataSetConfiguration to home and programs [DHIS2-19025]

src/pages/Appearance/Programs/__tests__/createInitialGlobalSpinner.test.js, src/pages/Appearance/Programs/helper.js
This PR adds a default value to global completion spinner.
[DHIS2-19398](https://jira.dhis2.org/browse/DHIS2-19398)
Default value: `false` (unchecked)
[DHIS2-19398]: https://dhis2.atlassian.net/browse/DHIS2-19398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: global completion spinner default value [DHIS2-19398]
